# This workflow should (just) publish a package to npm when a Git reference (Git branch or tag) in the workflow's repository is created
# see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#create

# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: publish to npm v1

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
